import type { InventoryItem } from "@/components/domain/stock/types";

/**
 * Centralized synthetic healthcare inventory catalog (UI-008ABCD §11),
 * spanning all ten categories. Deliberately varied `stockPolicy`
 * configurations (some with only `minimumStock`, some with the full
 * safety/reorder/maximum/leadTime set) so `resolveStockAttentionStatus`
 * (`features/stock/stock.ts`) exercises every bucket, and one inactive
 * item (`item-24`) to prove active/inactive display. No pricing/cost
 * field anywhere — this domain is quantity-based only (CLAUDE.md §30).
 *
 * `item-02` ("Compresses stériles 10×10") is deliberately the task's own
 * worked example (UI-008ABCD §22/§26/§43): minimum 25, safety stock 15,
 * reorder point 30, maximum 80, lead time 5 days, reorder quantity 30 —
 * combined with its movement history in `mock-movements-data.ts` this
 * reproduces "Stock actuel 18 / Minimum 25 / STOCK FAIBLE" exactly.
 */
export function getInventoryItemsMockData(): InventoryItem[] {
  return [
    {
      id: "item-01",
      itemNumber: "STK-0001",
      name: "Gants nitrile M",
      category: "medical_consumables",
      unit: "box",
      packageSize: "100 unités / boîte",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 10, reorderPoint: 15, maximumStock: 60 },
    },
    {
      id: "item-02",
      itemNumber: "STK-0002",
      name: "Compresses stériles 10×10",
      category: "medical_consumables",
      unit: "box",
      packageSize: "50 unités / boîte",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 25, safetyStock: 15, reorderPoint: 30, maximumStock: 80, reorderQuantity: 30, leadTimeDays: 5 },
    },
    {
      id: "item-03",
      itemNumber: "STK-0003",
      name: "Seringues 5 ml",
      category: "medical_consumables",
      unit: "box",
      packageSize: "100 unités / boîte",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 20, reorderPoint: 25 },
    },
    {
      id: "item-04",
      itemNumber: "STK-0004",
      name: "Cathéters IV 20G",
      category: "medical_consumables",
      unit: "box",
      packageSize: "50 unités / boîte",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 10, safetyStock: 5, reorderPoint: 15 },
    },
    {
      id: "item-05",
      itemNumber: "STK-0005",
      name: "Sérum physiologique 500 ml",
      category: "medical_consumables",
      unit: "bottle",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 12, safetyStock: 6, reorderPoint: 18 },
    },
    {
      id: "item-06",
      itemNumber: "STK-0006",
      name: "Lidocaïne 2 %",
      category: "medicines",
      unit: "vial",
      packageSize: "10 flacons / boîte",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      storageCondition: "ambient",
      medicineMetadata: { form: "Solution injectable", concentration: "2 %" },
      stockPolicy: { minimumStock: 8, safetyStock: 4, reorderPoint: 12 },
    },
    {
      id: "item-07",
      itemNumber: "STK-0007",
      name: "Antiseptique Bétadine",
      category: "medicines",
      unit: "bottle",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      storageCondition: "ambient",
      medicineMetadata: { form: "Solution externe", concentration: "10 %" },
      stockPolicy: { minimumStock: 6, safetyStock: 3, reorderPoint: 10 },
    },
    {
      id: "item-08",
      itemNumber: "STK-0008",
      name: "Vaccin antitétanique",
      category: "medicines",
      unit: "vial",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      storageCondition: "refrigerated",
      medicineMetadata: { form: "Solution injectable" },
      stockPolicy: { minimumStock: 5, safetyStock: 2, reorderPoint: 8 },
    },
    {
      id: "item-09",
      itemNumber: "STK-0009",
      name: "Fils de suture résorbables",
      category: "procedure_products",
      unit: "box",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 10, reorderPoint: 14 },
    },
    {
      id: "item-10",
      itemNumber: "STK-0010",
      name: "Gel échographie",
      category: "procedure_products",
      unit: "bottle",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 4, reorderPoint: 6 },
    },
    {
      id: "item-11",
      itemNumber: "STK-0011",
      name: "Électrodes ECG",
      category: "procedure_products",
      unit: "pack",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 6, reorderPoint: 10 },
    },
    {
      id: "item-12",
      itemNumber: "STK-0012",
      name: "Tests rapides (bandelettes)",
      category: "diagnostic_consumables",
      unit: "box",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 5, safetyStock: 2, reorderPoint: 8 },
    },
    {
      id: "item-13",
      itemNumber: "STK-0013",
      name: "Tubes de prélèvement",
      category: "diagnostic_consumables",
      unit: "box",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 15, reorderPoint: 20 },
    },
    {
      id: "item-14",
      itemNumber: "STK-0014",
      name: "Désinfectant instruments",
      category: "sterilization_infection_control",
      unit: "bottle",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 6, reorderPoint: 10 },
    },
    {
      id: "item-15",
      itemNumber: "STK-0015",
      name: "Solution hydroalcoolique",
      category: "sterilization_infection_control",
      unit: "bottle",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 10, reorderPoint: 15 },
    },
    {
      id: "item-16",
      itemNumber: "STK-0016",
      name: "Sachets de stérilisation",
      category: "sterilization_infection_control",
      unit: "pack",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 8, reorderPoint: 12 },
    },
    {
      id: "item-17",
      itemNumber: "STK-0017",
      name: "Masques FFP2",
      category: "ppe",
      unit: "box",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 15, safetyStock: 8, reorderPoint: 20 },
    },
    {
      id: "item-18",
      itemNumber: "STK-0018",
      name: "Gants stériles",
      category: "ppe",
      unit: "box",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 12, safetyStock: 6, reorderPoint: 18 },
    },
    {
      id: "item-19",
      itemNumber: "STK-0019",
      name: "Lames de bistouri",
      category: "disposable_medical_devices",
      unit: "box",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 8, reorderPoint: 12 },
    },
    {
      id: "item-20",
      itemNumber: "STK-0020",
      name: "Spéculums jetables",
      category: "disposable_medical_devices",
      unit: "pack",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 6, reorderPoint: 10 },
    },
    {
      id: "item-21",
      itemNumber: "STK-0021",
      name: "Pansements post-soins",
      category: "patient_aftercare",
      unit: "box",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 10, reorderPoint: 15 },
    },
    {
      id: "item-22",
      itemNumber: "STK-0022",
      name: "Kit d'oxygène (urgence)",
      category: "emergency_stock",
      unit: "kit",
      active: true,
      lotTracking: true,
      expirationTracking: true,
      stockPolicy: { minimumStock: 2, safetyStock: 1, reorderPoint: 3 },
    },
    {
      id: "item-23",
      itemNumber: "STK-0023",
      name: "Sacs déchets médicaux",
      category: "operational_stock",
      unit: "roll",
      active: true,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 5, reorderPoint: 8 },
    },
    {
      id: "item-24",
      itemNumber: "STK-0024",
      name: "Papier ECG",
      category: "operational_stock",
      unit: "roll",
      active: false,
      lotTracking: false,
      expirationTracking: false,
      stockPolicy: { minimumStock: 4, reorderPoint: 6 },
    },
  ];
}
