import type { Patient } from "./types";

/** Same fixed prototype "today" as Aujourd'hui/Agenda (UI-001/UI-002) — keeps the "Aujourd'hui" next-RDV filter meaningful. */
export { MOCK_BUSINESS_DATE as PATIENTS_TODAY_DATE } from "@/features/today/mock-data";

export const PRACTITIONERS = [
  { id: "pr-1", name: "Dr. Benali" },
  { id: "pr-2", name: "Dr. Amal" },
];

/** Synthetic Moroccan-context data only — no real patient information (CLAUDE.md §12, UI-003A §10). */
export function getPatientsMockData(): Patient[] {
  return [
    {
      id: "pat-1",
      patientNumber: "PAT-00281",
      firstName: "Ahmed",
      lastName: "El Mansouri",
      phone: "06 12 34 56 78",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: "2026-08-18",
      nextAppointment: { date: "2026-08-27", time: "10:30", service: "Consultation" },
      outstandingBalance: 1500,
      birthDate: "1992-03-10",
      cin: "BE482910",
      isSociallyCovered: true,
      insuranceRegime: "amo_cnss",
    },
    {
      id: "pat-2",
      patientNumber: "PAT-00282",
      firstName: "Sara",
      lastName: "Alaoui",
      phone: "06 23 45 67 89",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: "2026-08-20",
      nextAppointment: null,
      outstandingBalance: 0,
      birthDate: "1998-11-02",
      cin: "JT109345",
      isSociallyCovered: false,
    },
    {
      id: "pat-3",
      patientNumber: "PAT-00283",
      firstName: "Fatima",
      lastName: "Zahra",
      phone: "06 34 56 78 90",
      responsiblePractitionerId: "pr-2",
      responsiblePractitionerName: "Dr. Amal",
      lastVisit: "2026-08-23",
      nextAppointment: { date: "2026-08-23", time: "09:00" },
      outstandingBalance: 300,
    },
    {
      id: "pat-4",
      patientNumber: "PAT-00284",
      firstName: "Youssef",
      lastName: "Amrani",
      phone: "06 45 67 89 01",
      responsiblePractitionerId: "pr-2",
      responsiblePractitionerName: "Dr. Amal",
      lastVisit: "2026-08-23",
      nextAppointment: null,
      outstandingBalance: 0,
    },
    {
      id: "pat-5",
      patientNumber: "PAT-00285",
      firstName: "Karim",
      lastName: "Idrissi",
      phone: "06 56 78 90 12",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: "2026-07-30",
      nextAppointment: { date: "2026-08-23", time: "11:00" },
      outstandingBalance: 800,
    },
    {
      id: "pat-6",
      patientNumber: "PAT-00286",
      firstName: "Nadia",
      lastName: "El Fassi",
      phone: "06 67 89 01 23",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: null,
      nextAppointment: { date: "2026-08-23", time: "14:00" },
      outstandingBalance: 0,
    },
    {
      id: "pat-7",
      patientNumber: "PAT-00287",
      firstName: "Omar",
      lastName: "Bennani",
      phone: "06 78 90 12 34",
      responsiblePractitionerId: "pr-2",
      responsiblePractitionerName: "Dr. Amal",
      lastVisit: "2026-08-10",
      nextAppointment: null,
      outstandingBalance: 450,
    },
    {
      id: "pat-8",
      patientNumber: "PAT-00288",
      firstName: "Salma",
      lastName: "Tazi",
      phone: "06 89 01 23 45",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: "2026-08-23",
      nextAppointment: null,
      outstandingBalance: 0,
    },
    {
      id: "pat-9",
      patientNumber: "PAT-00289",
      firstName: "Mehdi",
      lastName: "Berrada",
      phone: "06 90 12 34 56",
      responsiblePractitionerId: "pr-2",
      responsiblePractitionerName: "Dr. Amal",
      lastVisit: "2026-06-15",
      nextAppointment: { date: "2026-09-02", time: "09:30" },
      outstandingBalance: 2200,
    },
    {
      id: "pat-10",
      patientNumber: "PAT-00290",
      firstName: "Imane",
      lastName: "Chraibi",
      phone: "06 12 39 87 45",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: "2026-08-05",
      nextAppointment: { date: "2026-08-30", time: "15:00" },
      outstandingBalance: 0,
    },
    {
      id: "pat-11",
      patientNumber: "PAT-00291",
      firstName: "Hind",
      lastName: "Squalli",
      phone: "06 23 48 76 51",
      responsiblePractitionerId: "pr-2",
      responsiblePractitionerName: "Dr. Amal",
      lastVisit: null,
      nextAppointment: null,
      outstandingBalance: 0,
    },
    {
      id: "pat-12",
      patientNumber: "PAT-00292",
      firstName: "Anas",
      lastName: "Benjelloun",
      phone: "06 34 59 87 12",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: "2026-08-12",
      nextAppointment: { date: "2026-08-25", time: "16:00" },
      outstandingBalance: 600,
    },
    {
      id: "pat-13",
      patientNumber: "PAT-00293",
      firstName: "Laila",
      lastName: "Fassi Fihri",
      phone: "06 45 61 23 78",
      responsiblePractitionerId: "pr-2",
      responsiblePractitionerName: "Dr. Amal",
      lastVisit: "2026-07-22",
      nextAppointment: null,
      outstandingBalance: 1200,
    },
    {
      id: "pat-14",
      patientNumber: "PAT-00294",
      firstName: "Rachid",
      lastName: "Ouazzani",
      phone: "06 56 72 34 89",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: "2026-08-19",
      nextAppointment: { date: "2026-08-24", time: "11:30" },
      outstandingBalance: 0,
    },
    {
      id: "pat-15",
      patientNumber: "PAT-00295",
      firstName: "Zineb",
      lastName: "Kabbaj",
      phone: "06 67 83 45 91",
      responsiblePractitionerId: "pr-2",
      responsiblePractitionerName: "Dr. Amal",
      lastVisit: "2026-08-01",
      nextAppointment: { date: "2026-09-05", time: "10:00" },
      outstandingBalance: 350,
    },
    {
      id: "pat-16",
      patientNumber: "PAT-00296",
      firstName: "Yassine",
      lastName: "Cherkaoui",
      phone: "06 78 94 56 12",
      responsiblePractitionerId: "pr-1",
      responsiblePractitionerName: "Dr. Benali",
      lastVisit: null,
      nextAppointment: { date: "2026-08-23", time: "16:30" },
      outstandingBalance: 0,
    },
  ];
}

/** Global empty state (UI-003A §27) — exercised by tests and the `state="empty"` prop. */
export function getEmptyPatientsMockData(): Patient[] {
  return [];
}
